export const LOAF_FRAME_THRESHOLD_MS = 500
export const STORE_MUTATION_THRESHOLD_MS = 250
export const PERSIST_WRITE_THRESHOLD_MS = 100
export const REACT_COMMIT_THRESHOLD_MS = 200
export const WATCHDOG_DRIFT_THRESHOLD_MS = 2000
